### ISSUE TITLE
listchars uses a different background

### ISSUE THREAD

**Issue by fedemp** [pacha/vem-dark#1] opened 2018-10-29 14:59 UTC
![1540825148](https://user-images.githubusercontent.com/735314/47658667-20eda500-db72-11e8-953a-55b1d3f92a1f.png)

**Comment by pacha** [comment] 2018-10-29 22:23
That's odd. The highlight group of listchars is `SpecialKey` and that's defined in vem-dark as:
```
highlight SpecialKey term=none cterm=none ctermfg=246 ctermbg=NONE guifg=#666666 guibg=NONE gui=none
```
which means that the characters should have the same background as normal text.

Can you execute: `:verbose highlight SpecialKey` to see where that background is coming from?

**Comment by pacha** [comment] 2019-01-01 19:44
Closing since I'm unable to reproduce the issue.

**Closed as completed by pacha** 2019-01-01 19:44 UTC
